<?php
/**
 * @file
 *   The Twitter Field Widget provides a custom field formatter to display
 *   Twitter Id's as Twitter Profile Widgets.
 */

/**
 * Implements hook_theme().
 */
function twitterfield_theme() {
  return array(
    'twitterfield_widget' => array(
      'variables' => array('twitter_id' => NULL),
      'template' => 'twitter-widget',
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function twitterfield_field_formatter_info() {
  return array(
    'twitterfield_widget' => array(
      'label' => t('Twitter Widget'),
      'field types' => array('text'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function twitterfield_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'twitterfield_widget':
      foreach ($items as $delta => $item) {
        if ($item['safe_value']) {
          $element[$delta] = array(
            '#markup' => theme('twitterfield_widget', array('twitter_id' => $item['safe_value'])),
          );
        }
      }
      break;
  }
  return $element;
}
